const sidebars = {
  docsSidebar: [
    { type: "doc", id: "overview" },
    {
      type: "category",
      label: "Milestones",
      items: [{ type: "autogenerated", dirName: "Milestones" }],
    },
    {
      type: "category",
      label: "Meetings",
      items: [{ type: "autogenerated", dirName: "meetings" }],
    },
    {
      type: "doc",
      id: "references",
    },
  ],
};

export default sidebars;
