const sidebars = {
  docsSidebar: [
    { type: "doc", id: "overview" },
    {
      type: "category",
      label: "Milestones",
      link: {
        type: "generated-index",
        title: "Milestones",
        description: "All project milestones organized by semester",
      },
      items: [
        {
          type: "category",
          label: "Semester 1",
          link: {
            type: "generated-index",
            title: "Semester 1",
            description: "Milestones from the first semester: MS1 - Inception, MS2 - Elaboration, MS3 - Construction",
          },
          items: [
            {
              type: "category",
              label: "MS1-Inception",
              link: {
                type: "generated-index",
                title: "MS1 - Inception",
              },
              items: [
                { type: "doc", id: "Semester 1/Milestones/MS1 - Inception/research_group"},
                { type: "doc", id: "Semester 1/Milestones/MS1 - Inception/context" },
                { type: "doc", id: "Semester 1/Milestones/MS1 - Inception/problems" },
                { type: "doc", id: "Semester 1/Milestones/MS1 - Inception/related_work" },
                { type: "doc", id: "Semester 1/Milestones/MS1 - Inception/goals" },
                { type: "doc", id: "Semester 1/Milestones/MS1 - Inception/expected_results" },
                { type: "doc", id: "Semester 1/Milestones/MS1 - Inception/deliverables" },
                { type: "doc", id: "Semester 1/Milestones/MS1 - Inception/calendar" },
              ],
            },
            {
              type: "category",
              label: "MS2-Elaboration",
              link: {
                type: "generated-index",
                title: "MS2 - Elaboration",
              },
              items: [
                { type: "doc", id: "Semester 1/Milestones/MS2 - Elaboration/deliverables" },
                { type: "doc", id: "Semester 1/Milestones/MS2 - Elaboration/Checkpoint1" },
                { type: "doc", id: "Semester 1/Milestones/MS2 - Elaboration/state_of_the_art" },
                { type: "doc", id: "Semester 1/Milestones/MS2 - Elaboration/requirements" },
                { type: "doc", id: "Semester 1/Milestones/MS2 - Elaboration/use_cases" },
                { type: "doc", id: "Semester 1/Milestones/MS2 - Elaboration/architecture" },
                { type: "doc", id: "Semester 1/Milestones/MS2 - Elaboration/domain_model" },
                { type: "doc", id: "Semester 1/Milestones/MS2 - Elaboration/dataset" },
                { type: "doc", id: "Semester 1/Milestones/MS2 - Elaboration/risk_management" },
                { type: "doc", id: "Semester 1/Milestones/MS2 - Elaboration/scope_definition" },
                { type: "doc", id: "Semester 1/Milestones/MS2 - Elaboration/mockups" },
                { type: "doc", id: "Semester 1/Milestones/MS2 - Elaboration/personas" },
              ],
            },
            {
              type: "category",
              label: "MS3-Construction",
              link: {
                type: "generated-index",
                title: "MS3 - Construction",
              },
              items: [
                { type: "autogenerated", dirName: "Semester 1/Milestones/MS3 - Construction" }
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Semester 2",
          link: {
            type: "generated-index",
            title: "Semester 2",
            description: "Milestones from the second semester: MS1 - Digital Accessibility and Usability, MS2 - Prototype",
          },
          items: [
            {
              type: "category",
              label: "MS1-Digital Accessibility and Usability",
              link: {
                type: "generated-index",
                title: "MS1 - Digital Accessibility and Usability",
              },
              items: [
                { type: "doc", id: "Semester 2/Milestones/MS1 - Digital Accessibility and Usability/Checkpoint4" },
                { type: "doc", id: "Semester 2/Milestones/MS1 - Digital Accessibility and Usability/Checkpoint5" },
                { type: "doc", id: "Semester 2/Milestones/MS1 - Digital Accessibility and Usability/deliverables" }
              ],
            },
            {
              type: "category",
              label: "MS2-Prototype",
              link: {
                type: "generated-index",
                title: "MS2 - Prototype",
              },
              items: [
                { type: "doc", id: "Semester 2/Milestones/MS2 - Prototype/deliverables" }
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Meetings",
      link: {
        type: "generated-index",
        title: "Project Meetings",
        description: "All meeting minutes and documentation from our project discussions.",
      },
      items: [
        // Manually specify meeting files in correct numeric order
        { type: "doc", id: "meetings/m1" },
        { type: "doc", id: "meetings/m2" },
        { type: "doc", id: "meetings/m3" },
        { type: "doc", id: "meetings/m4" },
        { type: "doc", id: "meetings/m5" },
        { type: "doc", id: "meetings/m6" },
        { type: "doc", id: "meetings/m7" },
        { type: "doc", id: "meetings/m8" },
        { type: "doc", id: "meetings/m9" },
        { type: "doc", id: "meetings/m10" },
        { type: "doc", id: "meetings/m11" },
        { type: "doc", id: "meetings/m12" },
        { type: "doc", id: "meetings/m13" },
        { type: "doc", id: "meetings/m14" },
      ],
    },
  ],
};

export default sidebars;
